# Generated by Django 4.0.4 on 2022-04-15 14:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlenderProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='projects')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratorTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('project_id', models.UUIDField()),
                ('data', models.TextField()),
                ('file_format', models.CharField(choices=[('glb', 'glb'), ('png', 'png')], default='png', max_length=5)),
                ('output_file', models.FileField(upload_to='outputs')),
                ('status', models.CharField(choices=[('created', 'Created'), ('running', 'Running'), ('completed', 'Completed'), ('error', 'Error')], default='created', max_length=10)),
                ('error', models.TextField(default='')),
            ],
        ),
    ]
