# Generated by Django 4.0.4 on 2022-05-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatortask',
            name='callback_url',
            field=models.CharField(default='', max_length=300),
        ),
    ]
