# Generated by Django 4.0.4 on 2022-05-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_generatortask_callback_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatortask',
            name='callback_url',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
