# Generated by Django 4.0.4 on 2022-05-16 17:07

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_generatortask_callback_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blenderproject',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to='projects'),
        ),
    ]
